import Head from 'next/head'
import {useShow} from "@/hooks/useShow";
import FadeInOnScroll from "@/components/FadeInOnScroll/FadeInOnScroll";
import {useRouter} from "next/router";
import {projects} from "@/content/projects";
import ImageWithPlaceholder from "@/components/ImageWithPlaceholder/ImageWithPlaceholder";

export default function Work() {

    const router = useRouter();
    const project = router.query.id ? projects[Number(router.query.id)] : projects[0];
    useShow();

    return (
        <>
            <Head>
                <title>anomalyy | Design group | {project.title}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="anim">
                <div className="works-category-bg fade-in reverse-delay-1 scale-down" style={{
                    backgroundImage: `linear-gradient(to bottom, rgba(16, 16, 16, 0.4), rgba(16, 16, 16, 1)), url("${project.bg}")`}}>

                </div>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 fade-in">
                            <h1 className="title">{project.title}</h1>
                            <h2 className="subtitle">Works</h2>
                        </div>
                        <div className="col-12">
                            {
                                project.works.map((work, index) => (
                                    <FadeInOnScroll key={index} defaultActive={index === 0}>
                                        <div className="work">
                                            {
                                                work.img ? (
                                                    <a href={work.link} target="_blank">
                                                        <ImageWithPlaceholder
                                                            src={work.img}
                                                            srcLow={work.imgLow}
                                                            alt="Image"
                                                            layout="fill"
                                                            objectFit="cover"
                                                            objectPosition="center"
                                                            className="img"
                                                            loading="lazy"
                                                        />
                                                    </a>
                                                ) : ""
                                            }
                                            {
                                                work.youtube ? (
                                                    <iframe width="100%" height="700px"
                                                            src={work.youtube}
                                                            style={{borderRadius: "8px"}}
                                                            title="YouTube video player" frameBorder="0"
                                                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                                                            allowFullScreen></iframe>
                                                ) : ""
                                            }

                                        </div>
                                    </FadeInOnScroll>
                                ))
                            }

                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}