import React from 'react';
import Head from "next/head";
import {useShow} from "@/hooks/useShow";

const About = () => {
    useShow();
    return (
        <>
            <Head>
                <title>anomalyy | About</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className={`anim`}>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 fade-in reverse-delay-2">
                            <h1 className="title">anomalyy<br/><span>Design group</span></h1>
                            <h2 className="subtitle">About us</h2>
                        </div>
                        <div className="col-lg-12 content-mt fade-in delay-2">
                            <p>

                                Hello, this design studio is created to provide strong design for anyone, no matter who you are (businessman, freelancer, fashion designer, artist, DJ, beatmaker, blogger, public figure, etc.).<br/><br/>
                                We handle projects of any complexity for your money. An artist should not be hungry; an artist should create powerful artwork and be stylish. If you choose Anomalyy Design Group, rest assured that you will receive the quality and style you desire.<br/><br/>
                                Style and quality are paramount. We will create the design exactly as you want it and as it should be. Anomalyy Studio is the plastic surgery in the field of design for your creations.<br/><br/>
                                Always in touch, yours Anomalyy Design Group.<br/><br/>
                                Design is not a toy for children.
                            </p>
                        </div>
                    </div>

                </div>
            </main>
        </>
    );
};

export default About;