import React from 'react';
import Head from "next/head";
import {useShow} from "@/hooks/useShow";

const Contact = () => {
    useShow();
    return (
        <>
            <Head>
                <title>anomalyy | Contact</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className={`anim`}>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 fade-in reverse-delay-2">
                            <h1 className="title">anomalyy<br/><span>Design group</span></h1>
                            <h2 className="subtitle">Contact us</h2>
                        </div>
                        <div className="col-lg-4 content-mt fade-in delay-2">
                            <p>
                                Telephone<br/>
                                <b><a href="tel:+7(926)-192-53-13" target="_blank">+7(926)-192-53-13</a></b><br/><br/>
                                Email<br/>
                                <b><a href="mailto:anomalyy_design@mail.ru" target="_blank">anomalyy_design@mail.ru</a></b><br/><br/>
                            </p>
                        </div>
                        <div className="col-lg-4 content-mt fade-in delay-2">
                            <p>
                                Telegram<br/>
                                <b><a href="https://t.me/AlexMercer2200" target="_blank">t.me/AlexMercer2200</a></b><br/><br/>
                                Instagram<br/>
                                <b><a href="https://instagram.com/anomalyy_dg" target="_blank">instagram.com/anomalyy_dg</a></b><br/><br/>
                                VK<br/>
                                <b><a href="https://vk.com/starostinsascha" target="_blank">vk.com/starostinsascha</a></b><br/><br/>
                            </p>
                        </div>
                        <div className="col-lg-4 content-mt fade-in delay-2">
                            <p>
                                FL.ru<br/>
                                <b><a href="https://www.fl.ru/users/starostinsasha2/portfolio" target="_blank">fl.ru/users/starostinsasha2/portfolio</a></b><br/><br/>
                                Upwork<br/>
                                <b><a href="https://www.upwork.com/nx/find-work/best-matches" target="_blank">upwork.com/nx/find-work/best-matches</a></b><br/><br/>
                                ArtStation<br/>
                                <b><a href="https://www.artstation.com/user-71393" target="_blank">artstation.com/user-71393</a></b><br/><br/>
                            </p>
                        </div>
                    </div>

                </div>
            </main>

        </>
    );
};

export default Contact;