import Head from 'next/head'
import ImageSlider from "@/components/ImageSlider/ImageSlider";
import {useState} from "react";
import ProjectSlider from "@/components/ProjectSlider/ProjectSlider";
import HelloScreen from "@/components/HelloScreen/HelloScreen";
import {projects} from "@/content/projects";
import {useTransition} from "@/hooks/useTransition";
import {useShow} from "@/hooks/useShow";

export default function Home() {
    const [activeSlide, setActiveSlide] = useState(0);

    const transition = useTransition();

    useShow(1600);

  return (
    <>
      <Head>
        <title>anomalyy | Design group</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={`fullscreen anim-delay`}>
        <div className="row-right">
            <div className="col-12" onClick={_ => setActiveSlide((activeSlide + 1) % 3)}>
                <ImageSlider slides={projects}
                activeSlide={activeSlide}
                />
            </div>
        </div>
          <ProjectSlider
            slides={projects}
            setActiveSlide={setActiveSlide}
            activeSlide={activeSlide}
            transition={transition}
          />
      </main>
        <HelloScreen/>
    </>
  )
}
