import React from 'react';
import {useShow} from "@/hooks/useShow";
import Head from "next/head";
import FadeInOnScroll from "@/components/FadeInOnScroll/FadeInOnScroll";
import {news} from "@/content/news"

const News = () => {
    useShow();
    return (
        <>
            <Head>
                <title>anomalyy | News</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className={`anim`}>
                <div className="container">
                    <div className="row">
                        <div className="col-lg-12 fade-in reverse-delay-2">
                            <h1 className="title">anomalyy<br/><span>News</span></h1>
                        </div>
                        {news.map((n, index) => (
                            <FadeInOnScroll key={index} defaultActive={index === 0}>
                                <div className="col-lg-12 content-mt fade-in reverse-delay-2">
                                    <h2 className="">{n.title}</h2><br/>
                                </div>
                                <div className="col-lg-12 fade-in delay-2">
                                    <p>
                                        {n.description}
                                    </p>
                                </div>
                            </FadeInOnScroll>
                        ))}

                    </div>

                </div>
            </main>
        </>
    );
};

export default News;